// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvnficchfmtivgjjkpcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bmZpY2NoZm10aXZnamprcGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTQzNDIsImV4cCI6MjA3MDg3MDM0Mn0.xaV0PZc69O4SPWGLwy7SPUicQVrq8HF7WQKFWx1EN-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});